# Copyright (c) 2025-2026 SandAI. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dataclasses import dataclass

import torch
from torch.nn.attention.flex_attention import create_block_mask

import magi_attention
from magi_attention.common import AttnRanges
from magi_attention.utils import format_dict_field, format_list_field

is_magi_to_hstu_installed = False
try:
    import magi_to_hstu_cuda

    is_magi_to_hstu_installed = True
except ImportError:
    pass

is_fa4_installed = False
try:
    from flash_attn.cute.block_sparsity import (
        BlockSparseTensorsTorch,
        bhqk_to_linear_sparse_tensors,
    )
    from flash_attn.cute.mask_definitions import flex_arbitrary_mask

    is_fa4_installed = True
except ImportError:
    pass

COMPUTE_CAPABILITY = torch.cuda.get_device_capability()[0]


@dataclass(repr=False)
class AttnArg:
    q_ranges: AttnRanges
    k_ranges: AttnRanges
    attn_type_map: list[int]

    # total area of the attn arg, -1 means unknown
    total_area: int = -1

    # NOTE: The following variables are automatically generated by `__post_init__`
    # and serve as the meta arguments for ffa kernels in dist-attn.
    #   ffa_fwd_args_dict: dict
    #   skip_attn_fwd: bool
    #   disable_fwd_atomic_reduction: bool
    #
    #   q_ranges_bwd: AttnRanges
    #   k_ranges_bwd: AttnRanges
    #   attn_type_map_bwd: list[int]
    #   ffa_bwd_args_dict: dict
    #   skip_attn_bwd: bool
    #   disable_bwd_dkv_atomic_reduction: bool

    def __post_init__(self):
        # shape check
        assert len(self.q_ranges) == len(self.k_ranges) == len(self.attn_type_map)

        # init fwd ffa args dict
        # NOTE: we need to init fwd args first before bwd args
        self._init_ffa_fwd_args_dict()

        # init ffa args for bwd
        self._init_ffa_bwd_args_dict()

    def _init_ffa_fwd_args_dict(self) -> None:
        # init `skip_attn_fwd` flag
        batch_size_fwd = len(self.q_ranges)
        self.skip_attn_fwd = batch_size_fwd == 0

        # init `disable_fwd_atomic_reduction` flag
        self.disable_fwd_atomic_reduction = self.q_ranges.is_non_overlap()

        # init tensors
        q_ranges_tensor_fwd = self.q_ranges.to_tensor(
            device=torch.cuda.current_device()
        )
        k_ranges_tensor_fwd = self.k_ranges.to_tensor(
            device=torch.cuda.current_device()
        )
        mask_type_tensor_fwd = torch.tensor(
            self.attn_type_map,
            dtype=torch.int32,
            device=torch.cuda.current_device(),
        )

        # sanity check
        if magi_attention.is_sanity_check_enable():
            # check tensor shape
            if not self.skip_attn_fwd:
                assert q_ranges_tensor_fwd.shape == torch.Size([batch_size_fwd, 2])
                assert k_ranges_tensor_fwd.shape == torch.Size([batch_size_fwd, 2])
                assert mask_type_tensor_fwd.shape == torch.Size([batch_size_fwd])

        self.ffa_fwd_args_dict = dict(
            q_ranges=q_ranges_tensor_fwd,
            k_ranges=k_ranges_tensor_fwd,
            attn_type_map=mask_type_tensor_fwd,
        )

    def _init_ffa_bwd_args_dict(self) -> None:
        # just copy args from fwd
        self.skip_attn_bwd = self.skip_attn_fwd
        self.q_ranges_bwd = self.q_ranges
        self.k_ranges_bwd = self.k_ranges
        self.attn_type_map_bwd = self.attn_type_map

        self.ffa_bwd_args_dict = self.ffa_fwd_args_dict

        # init `disable_bwd_dkv_atomic_reduction` flag
        # FIXME: some bug with this flag, thus set to False temporarily
        # self.disable_bwd_dkv_atomic_reduction = self.k_ranges_bwd.is_non_overlap()
        self.disable_bwd_dkv_atomic_reduction = False

    def to_ffa_args(self, is_bwd: bool = False) -> dict:
        return self.ffa_bwd_args_dict if is_bwd else self.ffa_fwd_args_dict

    def can_skip(self, is_bwd: bool = False) -> bool:
        return self.skip_attn_bwd if is_bwd else self.skip_attn_fwd

    def __repr__(self) -> str:
        indent = ""
        repr_str = "AttnArg(\n"

        repr_str += f"{indent}    q_ranges={repr(self.q_ranges)},\n"
        repr_str += f"{indent}    k_ranges={repr(self.k_ranges)},\n"
        repr_str += f"{indent}    attn_type_map={self.attn_type_map},\n"
        repr_str += f"{indent}    total_area={self.total_area},\n"

        repr_str += f"{indent}    # Generated by __post_init__ (fwd):\n"
        repr_str += format_dict_field(
            "ffa_fwd_args_dict", self.ffa_fwd_args_dict, indent
        )
        repr_str += f"{indent}    skip_attn_fwd={self.skip_attn_fwd},\n"
        repr_str += f"{indent}    disable_fwd_atomic_reduction={self.disable_fwd_atomic_reduction},\n"

        repr_str += f"{indent}    # Generated by __post_init__ (bwd):\n"
        repr_str += f"{indent}    q_ranges_bwd={repr(self.q_ranges_bwd)},\n"
        repr_str += f"{indent}    k_ranges_bwd={repr(self.k_ranges_bwd)},\n"
        repr_str += f"{indent}    attn_type_map_bwd={self.attn_type_map_bwd},\n"
        repr_str += format_dict_field(
            "ffa_bwd_args_dict", self.ffa_bwd_args_dict, indent
        )
        repr_str += f"{indent}    skip_attn_bwd={self.skip_attn_bwd},\n"
        repr_str += f"{indent}    disable_bwd_dkv_atomic_reduction={self.disable_bwd_dkv_atomic_reduction},\n"

        repr_str = repr_str.rstrip(",\n") + "\n)"
        return repr_str


@dataclass(repr=False)
class FA4AttnArg(AttnArg):
    tile_m: int = 128
    tile_n: int = 128

    def __post_init__(self):
        assert is_fa4_installed, "FlashAttn4 is not installed"
        assert is_magi_to_hstu_installed, "magi_to_hstu_cuda is not installed"

        if COMPUTE_CAPABILITY == 10 and (self.tile_m, self.tile_n) != (128, 128):
            raise ValueError(
                "TODO: Non-128x128 tiles currently not supported on SM 10.0. due to TMEM"
            )

        super().__post_init__()

        # Transfer from FFA args to FA4 args
        self._transfer_ffa_args_to_fa4_args()

        # Clear FFA args
        self.ffa_fwd_args_dict.clear()
        self.ffa_bwd_args_dict.clear()

    def _transfer_ffa_args_to_fa4_args(self) -> None:
        # Get meta FA4 args
        self.seqlen_q = self.q_ranges.end
        self.seqlen_k = self.k_ranges.end
        self.n_max_func = magi_attention.functional.fa4_hsfu_max_num_funcs()

        # Transfer representation of attn mask
        # from AttnSlice to HSTU Functions
        # where hstu_func: shape=(nfunc, sq)
        #   and unsqueeze to shape=(1, 1, nfunc, sq) to be broadcastable
        hstu_func = (
            magi_to_hstu_cuda.magi_to_hstu(
                q_ranges=self.ffa_fwd_args_dict["q_ranges"],
                k_ranges=self.ffa_fwd_args_dict["k_ranges"],
                mask_types=self.ffa_fwd_args_dict["attn_type_map"],
                seqlen_q=self.seqlen_q,
                seqlen_k=self.seqlen_k,
                n_max_func=self.n_max_func,
            )
            .unsqueeze(0)
            .unsqueeze(0)
        )
        aux_tensors = [hstu_func]

        # DE-BUG:
        # print(f'{hstu_func.shape=} | {self.seqlen_q=} | {self.seqlen_k=} | {self.n_max_func=}\n')
        # print(f'{self.ffa_fwd_args_dict["q_ranges"]=} | {self.ffa_fwd_args_dict["k_ranges"]=}\n')
        # print(f'{self.ffa_fwd_args_dict["attn_type_map"]=} | {hstu_func=}\n')
        # torch.save(self.ffa_fwd_args_dict["q_ranges"], "q_ranges.pt")
        # torch.save(self.ffa_fwd_args_dict["k_ranges"], "k_ranges.pt")
        # torch.save(self.ffa_fwd_args_dict["attn_type_map"], "attn_type_map.pt")
        # torch.save(hstu_func, "hstu_func.pt")

        # Compute block sparsity for mask_mod
        if COMPUTE_CAPABILITY == 10:
            sparse_tile_m = 2 * self.tile_m
        else:
            sparse_tile_m = self.tile_m

        # Prepare mask_mod
        def mask_mod_flex(b, h, q_idx, kv_idx, arbitrary_func=hstu_func):
            return flex_arbitrary_mask(b, h, q_idx, kv_idx, arbitrary_func)

        # Preare linear block sparse mask of k for forward
        bm = create_block_mask(
            mask_mod_flex,
            1,
            1,
            self.seqlen_q,
            self.seqlen_k,
            device="cuda",
            BLOCK_SIZE=(sparse_tile_m, self.tile_n),
        )
        _, _, k_mask_cnt, k_mask_idx, k_full_cnt, k_full_idx, *_ = bm.as_tuple()
        k_block_sparse_mask = BlockSparseTensorsTorch(
            mask_block_cnt=k_mask_cnt,
            mask_block_idx=k_mask_idx,
            full_block_cnt=k_full_cnt,
            full_block_idx=k_full_idx,
        )
        linear_k_block_sparse_mask = bhqk_to_linear_sparse_tensors(k_block_sparse_mask)

        # Preare linear block sparse mask of q for backward
        bm_bwd = create_block_mask(
            mask_mod_flex,
            1,
            1,
            self.seqlen_q,
            self.seqlen_k,
            device="cuda",
            BLOCK_SIZE=(self.tile_m, self.tile_n),
        )
        (
            _,
            _,
            _,
            _,
            _,
            _,
            q_mask_cnt,
            q_mask_idx,
            q_full_cnt,
            q_full_idx,
            *_,
        ) = bm_bwd.as_tuple()
        q_block_sparse_mask = BlockSparseTensorsTorch(
            mask_block_cnt=q_mask_cnt,
            mask_block_idx=q_mask_idx,
            full_block_cnt=q_full_cnt,
            full_block_idx=q_full_idx,
        )
        linear_q_block_sparse_mask = bhqk_to_linear_sparse_tensors(q_block_sparse_mask)

        # Prepare FA4 args for both forward and backward
        self.fa4_fwd_args_dict = dict(
            linear_k_block_sparse_mask=linear_k_block_sparse_mask,
            linear_q_block_sparse_mask=linear_q_block_sparse_mask,
            aux_tensors=aux_tensors,
        )
        self.fa4_bwd_args_dict = self.fa4_fwd_args_dict

    def to_fa4_args(self, is_bwd: bool = False) -> dict:
        return self.fa4_bwd_args_dict if is_bwd else self.fa4_fwd_args_dict

    def to_ffa_args(self, is_bwd: bool = False) -> dict:
        raise RuntimeError("FA4AttnArg does not support to_ffa_args")

    def can_skip(self, is_bwd: bool = False) -> bool:
        return False


@dataclass(repr=False)
class CalcMeta:
    local_attn_arg: AttnArg
    remote_attn_args_list: list[AttnArg]

    @property
    def overlap_degree(self) -> int:
        return len(self.remote_attn_args_list)

    def __post_init__(self):
        assert (
            self.overlap_degree >= 1
        ), f"Overlap degree must be >= 1, but got {self.overlap_degree=}"

        if magi_attention.is_fa4_backend_enable():
            self.local_attn_arg = FA4AttnArg(
                q_ranges=self.local_attn_arg.q_ranges,
                k_ranges=self.local_attn_arg.k_ranges,
                attn_type_map=self.local_attn_arg.attn_type_map,
                total_area=self.local_attn_arg.total_area,
            )

            for stage in range(self.overlap_degree):
                remote_attn_arg = self.remote_attn_args_list[stage]
                self.remote_attn_args_list[stage] = FA4AttnArg(
                    q_ranges=remote_attn_arg.q_ranges,
                    k_ranges=remote_attn_arg.k_ranges,
                    attn_type_map=remote_attn_arg.attn_type_map,
                    total_area=remote_attn_arg.total_area,
                )

    def __repr__(self) -> str:
        indent = ""
        repr_str = f"CalcMeta(overlap_degree={self.overlap_degree},\n"

        # local_attn_arg
        local_attn_arg_repr_lines = repr(self.local_attn_arg).splitlines()
        repr_str += f"{indent}    local_attn_arg={local_attn_arg_repr_lines[0]}\n"
        for line in local_attn_arg_repr_lines[1:]:
            repr_str += f"{indent}    {line}\n"

        # remote_attn_args_list
        repr_str += format_list_field(
            "remote_attn_args_list", self.remote_attn_args_list, indent
        )

        repr_str = repr_str.rstrip(",\n") + "\n)"
        return repr_str
